image: ghcr.io/arch-r/boruta-testing:latest

stages:
  - base
  - check

r-base:
  stage: base
  script:
    - R -e "devtools::document()"
    - R -e "devtools::build('.','.')"
    - R -e "devtools::test()"
    - R -e "covr::codecov(quiet=FALSE,type='all')"
    - R CMD check Boruta_*.tar.gz
  artifacts:
    paths:
      - man/
      - NAMESPACE
      - Boruta_*.tar.gz
      - Boruta.Rcheck/

r-dev-check:
  stage: check
  script:
    - RD CMD check Boruta_*.tar.gz
  artifacts:
    paths:
      - Boruta.Rcheck/
